version: "3.8"

services:
  backend:
    image: classroom-${ENV_NAME}-backend:latest
    env_file:
      - .env # <--- เปลี่ยนมาอ่าน .env ตัวแม่ (ไฟล์เดียวจบ)
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-internal-${ENV_NAME}
      - traefik-public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${ENV_NAME}_backend.rule=Host(`${API_DOMAIN}`)"
        - "traefik.http.services.${ENV_NAME}_backend.loadbalancer.server.port=8000"

  frontend: # <--- เปลี่ยนชื่อจาก frontend_ts เป็น frontend
    image: classroom-${ENV_NAME}-frontend:latest
    networks:
      - traefik-public
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${ENV_NAME}_frontend.rule=Host(`${WEB_DOMAIN}`)"
        - "traefik.http.services.${ENV_NAME}_frontend.loadbalancer.server.port=80"

  bot_discord:
    image: classroom-${ENV_NAME}-bot:latest
    env_file:
      - .env # <--- เปลี่ยนมาอ่าน .env ตัวแม่ด้วย
    networks:
      - app-internal-${ENV_NAME}
    deploy:
      replicas: 1
      update_config:
        order: stop-first

networks:
  traefik-public:
    external: true
  app-internal-staging:
    external: true
  app-internal-production:
    external: true